project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Statistical Learning using Python"
  subtitle: "The R4DS Online Learning Community"
  site-url: https://hastie.su.domains/ISLP/ISLP_website.pdf
  repo-url: https://github.com/r4ds/bookclub-islp
  sharing: [twitter, facebook, linkedin]

  chapters:
    - index.qmd
    - part: 01_main.qmd
      chapters:
        - 01_notes.qmd
        - 01_video.qmd
    - part: 02_main.qmd
      chapters:
        - 02_notes.qmd
        - 02_video.qmd
    # - part: examples.md
    #   chapters:
    #     - example_quarto.qmd
    #     - example_python.ipynb
  appendices:
    - how-to.qmd

format:
  html:
    theme: cosmo
    fontsize: 16pt
    css: style.css
    include-in-header: sidebars-toggle.html

execute:
  freeze: true
